spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: root

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true